version: "3.9"
services:
  wouldyou-bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
    - "4959"
    stdin_open: true 
    tty: true
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
      - TAG=DOCKER
    network_mode: "host"
    labels:
      gg.wouldyou.compose-author: "Discord username 536b656c6c79 "
