productionId: '981649513427111957'

links:
  invite: https://wouldyoubot.gg/invite
  website: https://wouldyoubot.gg/
  support: https://wouldyoubot.gg/discord
  vote: https://wouldyoubot.gg/vote
  tos: https://wouldyoubot.gg/terms
  privacy: https://wouldyoubot.gg/privacy

developers:
  - '340243638892101646' # Sean
  - '347077478726238228' # Mezo
  - '268843733317976066' # Sky
  - '799319682862809169' # Marc
