name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm lint

      - name: Compile the TypeScript
        run: npm run build

      - name: Run prettier
        run: npm format:check

      - name: Send Discord error notification
        if: ${{ failure() }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"Integration check failed!"}' \
               https://discord.com/api/webhooks/1108169734542872686/t7Ih5eRKmUFbZii8mBu-GCSzJ4MgRwgHlMuQHLwzZnApQrb1G7f4prKVgGSp8lOtBGpw
